{% set name = "httpx" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0cb88a46f32dc874e04ee956e4c2764aba2aa228f650b06788ba6bda2962ab5
  patches:
    - patches/0001-remove-fancy-pypi-readme.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # no httpcore>=1 for s390x
  skip: True  # [py<38 or s390x]
  entry_points:
    - httpx = httpx:main

requirements:
  build:
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - certifi
    - httpcore >=1,<2
    - anyio
    - idna
    - sniffio
  run_constrained:
    - click >=8,<9
    - pygment >=2,<3
    - rich >=10,<14
    - h2 >=3,<5
    - socksio >=1,<2

# We're not getting the same list but the same kinds errors are in
# https://github.com/encode/httpx/discussions/2270
{% set tests_to_skip = "" %}
{% set tests_to_skip = tests_to_skip + " test_help" %}                              # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_get" %}                               # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_json" %}                              # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_binary" %}                            # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_redirects" %}                         # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_follow_redirects" %}                  # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_post" %}                              # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_verbose" %}                           # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_auth" %}                              # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_download" %}                          # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_errors" %}                            # KeyError: 'prog_name'
{% set tests_to_skip = tests_to_skip + " or test_socks_proxy_deprecated" %}            # socksio
{% set tests_to_skip = tests_to_skip + " or test_socks_proxy" %}                       # socksio
{% set tests_to_skip = tests_to_skip + " or test_multipart_encode_files_raises_exception_with_text_mode_file" %}  # [win] no TypeError
{% set tests_to_skip = tests_to_skip + " or test_write_timeout[asyncio]" %}            # [win] no httpx.WriteTimeout
{% set tests_to_skip = tests_to_skip + " or test_logging_ssl" %}                       # [win] \\ -> \\\\ ?

test:
  source_files:
    - tests
  imports:
    - httpx
  requires:
    - pip
    - pytest
    # You want brotli-python here rather than just the brotli that
    # "import brotli" might imply
    - brotli-python
    - chardet
    - trio
    - trustme
    - uvicorn
    - h2
  commands:
    - pip check
    - pytest -vv tests -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  description: |
    HTTPX is a fully featured HTTP client library for Python 3.
    It includes an integrated command line client, has support
    for both HTTP/1.1 and HTTP/2, and provides both sync and async APIs.
  doc_url: https://www.python-httpx.org
  dev_url: https://github.com/encode/httpx

extra:
  recipe-maintainers:
    - primozgodec
    - florimondmanca
    - thewchan
