{% set name = "httpx" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8e778f76d9bbd46af49e7f062467e3157a5a3d2ae4876a4bbfd8a51ed9c9cb4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - certifi
    - sniffio
    - idna ==2.*
    - rfc3986 >=1.3,<2
    - httpcore >=0.13.0,<0.14.0
    - async_generator  # [py<37]
    # http2 is optional
    - h2 ==3.*
    # brotcliffi is optional (see https://github.com/encode/httpx/blob/master/README.md)
    #- brotlicffi==1.*

test:
  imports:
    - httpx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  doc_url: https://www.python-httpx.org/
  dev_url: https://github.com/encode/httpx

extra:
  recipe-maintainers:
    - primozgodec
    - florimondmanca
