{% set name = "httpx" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 451b55c30d5185ea6b23c2c793abf9bb237d2a7dfb901ced6ff69ad37ec1dfaf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [python_impl == 'pypy' and py==37]
  skip: True  # [py<36 or s390x]

requirements:
  host:
    - pip
    - wheel
    - setuptools
    - python
  run:
    - python
    - certifi
    - httpcore ==1.*
    - anyio
    - idna
    - sniffio

test:
  imports:
    - httpx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  description: |
    HTTPX is a fully featured HTTP client library for Python 3.
    It includes an integrated command line client, has support
    for both HTTP/1.1 and HTTP/2, and provides both sync and async APIs.
  doc_url: https://www.encode.io/httpx/
  dev_url: https://github.com/encode/httpx

extra:
  recipe-maintainers:
    - primozgodec
    - florimondmanca
    - thewchan
