{% set name = "httpx" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0cb88a46f32dc874e04ee956e4c2764aba2aa228f650b06788ba6bda2962ab5
  patches:
    - patches/0001-remove-fancy-pypi-readme.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # no httpcore>=1 for s390x
  skip: True  # [py<38 or s390x]
  entry_points:
    - httpx = httpx:main

requirements:
  build:
    - patch     # [unix]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - certifi
    - httpcore >=1,<2
    - anyio
    - idna
    - sniffio
  run_constrained:
    - click >=8,<9
    - pygment >=2,<3
    - rich >=10,<14
    - h2 >=3,<5
    - socksio >=1,<2

test:
  imports:
    - httpx
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/encode/httpx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: A next-generation HTTP client for Python.
  description: |
    HTTPX is a fully featured HTTP client library for Python 3.
    It includes an integrated command line client, has support
    for both HTTP/1.1 and HTTP/2, and provides both sync and async APIs.
  doc_url: https://www.python-httpx.org
  dev_url: https://github.com/encode/httpx

extra:
  recipe-maintainers:
    - primozgodec
    - florimondmanca
    - thewchan
